### ISSUE TITLE
T4_Diagrama de secuencia

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-systems#1]
[T4_DIAGRAMA DE SECUENCIAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-systems/files/7824942/T4_DIAGRAMA.DE.SECUENCIAS.pdf)

**Comment by ArturoAngonJose** [comment]
Calificacion:30/30

**Comment by josealfredo79** [comment]
bien hecho y revisado
